# Generated by Django 4.1 on 2025-03-24 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastName', models.TextField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.TextField(max_length=320, validators=[django.core.validators.MinLengthValidator(5)])),
                ('password', models.TextField(validators=[django.core.validators.MinLengthValidator(2)])),
                ('paymentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role')),
            ],
        ),
    ]
