# Generated by Django 4.1 on 2025-03-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release', models.DateField()),
                ('cover', models.TextField()),
                ('oneStarCount', models.PositiveBigIntegerField()),
                ('twoStarCount', models.PositiveBigIntegerField()),
                ('threeStarCount', models.PositiveBigIntegerField()),
                ('fourStarCount', models.PositiveBigIntegerField()),
                ('fiveStarCount', models.PositiveBigIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('category', models.ManyToManyField(related_name='books', to='book.category')),
            ],
        ),
    ]
