# Generated by Django 5.1.7 on 2025-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fiveStarCount',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='fourStarCount',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='oneStarCount',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='threeStarCount',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='twoStarCount',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
