# Generated by Django 4.1 on 2025-03-24 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('name', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(4)])),
                ('number', models.PositiveBigIntegerField(max_length=19, primary_key=True, serialize=False)),
                ('cvc', models.PositiveSmallIntegerField(max_length=4)),
                ('expiration', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
    ]
