# Generated by Django 5.1.7 on 2025-03-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
