# Generated by Django 5.1.7 on 2025-03-31 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_cvc_alter_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
